'use client';
import { useEffect, useRef, useCallback, useState } from 'react';
import { useParams, useRouter, useSearchParams } from 'next/navigation';
import { useAuthStore } from '@/store/auth.store';
import { useCanvasStore } from '@/store/canvas.store';
import { useUIStore } from '@/store/ui.store';
import { useCollaboration } from '@/lib/socket/useCollaboration';
import { useVoice } from '@/lib/socket/useVoice';
import { canvasApi } from '@/lib/api/canvas.api';
import { elementApi } from '@/lib/api/element.api';
import { exportCanvas } from '@/lib/export';
import { toAPI, generateId } from '@/lib/element.transform';
import { DrawableElement, FlowchartElement, FLOWCHART_DEFAULTS, isStroke, isShape, isFlowchart, isTextElement } from '@/types/element';
import { CanvasEngine } from '@/components/canvas/CanvasEngine';
import { Toolbar } from '@/components/canvas/Toolbar';
import { TopBar } from '@/components/canvas/TopBar';
import { AIChatPanel } from '@/components/ai/AIChatPanel';
import { GhostAcceptBar } from '@/components/ai/GhostAcceptBar';
import { VoiceRoom } from '@/components/voice/VoiceRoom';
import { ShareModal } from '@/components/share/ShareModal';
import { AnnotationsPanel } from '@/components/canvas/AnnotationsPanel';
import { BranchHistoryPanel } from '@/components/canvas/BranchHistoryPanel';
import { ToastContainer } from '@/components/ui/Toast';
import { thumbnailApi } from '@/lib/api/ai.api';

export default function CanvasPage() {
  const params = useParams();
  const router = useRouter();
  const searchParams = useSearchParams();
  const canvasId = String(params.id);
  // shareToken is passed in the URL query by the join/[token] redirect page
  const shareToken = searchParams.get('shareToken') ?? undefined;
  const canvasElemRef = useRef<HTMLCanvasElement | null>(null);

  const { firebaseUser, loading: authLoading, getToken } = useAuthStore();
  const { role, history, historyIndex, undo, redo, elements, deletedIds,
    addElement, pushHistory, init, setLastSaved, setIsSyncing, replaceElements, markDeleted,
  } = useCanvasStore();
  const { addToast } = useUIStore();

  const [token, setToken] = useState('');
  const [joinLoading, setJoinLoading] = useState(true);
  const [joiningVoice, setJoiningVoice] = useState(false);
  // Ghost elements generated by AI Agent
  const [ghostElements, setGhostElements] = useState<DrawableElement[]>([]);

  const canEdit = role === 'owner' || role === 'editor';

  // ── Auth guard ───────────────────────────────────────────────────────────────
  useEffect(() => {
    if (!authLoading && !firebaseUser) router.replace('/login');
  }, [authLoading, firebaseUser, router]);

  // ── Fetch token + load canvas ────────────────────────────────────────────────
  useEffect(() => {
    if (!firebaseUser || !canvasId) return;
    (async () => {
      const t = await getToken() ?? '';
      setToken(t);
      try {
        // Pass shareToken so backend resolveRole() grants access via share link
        const { canvas } = await canvasApi.get(canvasId, shareToken);
        init({ canvasId, title: canvas.title, role: canvas.myRole ?? 'viewer', shareToken });
      } catch (err: any) {
        const msg = err?.response?.data?.error?.message ?? 'Failed to load canvas';
        addToast(msg, 'error');
        router.replace('/dashboard');
      } finally {
        setJoinLoading(false);
      }
    })();
  }, [firebaseUser, canvasId, shareToken, getToken, init, addToast, router]);

  // ── Socket.IO collaboration ──────────────────────────────────────────────────
  const {
    socket,
    mySocketId,
    emitElementAdd,
    emitElementUpdate,
    emitElementDelete,
    emitElementsBatch,
    emitCursorMove,
    emitStrokePreview,
    emitCanvasClear,
    emitCanvasSave,
    emitAIRequest,
  } = useCollaboration({
    canvasId,
    token,
    shareToken, // ← pass shareToken so socket canvas:join is authorised for share-link users
    onCanvasJoined: (data) => {
      if (data.lastViewport) {
        const { setViewport } = useCanvasStore.getState();
        setViewport(data.lastViewport);
      }
    },
  });

  // ── Voice ────────────────────────────────────────────────────────────────────
  const { inVoice, muted, participants, permissionDenied, joinVoice, leaveVoice, toggleMute } = useVoice({
    socket, canvasId, mySocketId,
  });

  const handleJoinVoice = async () => {
    setJoiningVoice(true);
    await joinVoice();
    setJoiningVoice(false);
  };

  // ── Save ─────────────────────────────────────────────────────────────────────
  const handleSave = useCallback(async (silent = false) => {
    setIsSyncing(true);
    try {
      const apiElements = elements.map(toAPI);
      await elementApi.bulkSave(canvasId, apiElements, deletedIds, useCanvasStore.getState().viewport);
      setLastSaved(new Date());
      if (!silent) addToast('Saved', 'success', 2000);
      useCanvasStore.getState().clearDeletedIds();
    } catch {
      if (!silent) addToast('Save failed', 'error');
    } finally {
      setIsSyncing(false);
    }
  }, [canvasId, elements, deletedIds, setIsSyncing, setLastSaved, addToast]);

  // Auto-save every 30 seconds
  useEffect(() => {
    if (!canEdit) return;
    const interval = setInterval(() => {
      // Only auto-save if elements or deleted array length has changed (rough proxy vs checking full diffs)
      handleSave(true);
    }, 30000);
    return () => clearInterval(interval);
  }, [canEdit, handleSave]);

  // ── Undo / Redo ───────────────────────────────────────────────────────────────
  const broadcastDiff = useCallback((prevElements: DrawableElement[], currentElements: DrawableElement[]) => {
    const prevIds = new Set(prevElements.map(e => e.id));
    const currentIds = new Set(currentElements.map(e => e.id));
    
    const deletedIds = currentElements.filter(e => !prevIds.has(e.id)).map(e => String(e.id));
    const added = prevElements.filter(e => !currentIds.has(e.id)).map(toAPI);
    const updated = prevElements.filter(e => currentIds.has(e.id)).map(toAPI);
    
    if (added.length > 0 || updated.length > 0 || deletedIds.length > 0) {
      emitElementsBatch(added, updated, deletedIds);
    }
  }, [emitElementsBatch]);

  const handleUndo = useCallback(() => {
    const currentElements = useCanvasStore.getState().elements;
    const prev = undo();
    if (prev) {
      replaceElements(() => prev);
      broadcastDiff(prev, currentElements);
    }
  }, [undo, replaceElements, broadcastDiff]);

  const handleRedo = useCallback(() => {
    const currentElements = useCanvasStore.getState().elements;
    const next = redo();
    if (next) {
      replaceElements(() => next);
      broadcastDiff(next, currentElements);
    }
  }, [redo, replaceElements, broadcastDiff]);

  // ── Handle element events ──────────────────────────────────────────────────────
  const handleElementAdd = useCallback((_el: DrawableElement, apiForm: unknown) => {
    emitElementAdd(apiForm);
  }, [emitElementAdd]);

  const handleElementDelete = useCallback((ids: string[]) => {
    ids.forEach(id => {
      useCanvasStore.getState().markDeleted(id);
      useCanvasStore.getState().removeElement(id);
    });
    emitElementDelete(ids);
  }, [emitElementDelete]);

  // ── Thumbnails ────────────────────────────────────────────────────────────────
  const handleThumbnailCapture = useCallback(async (dataUrl: string) => {
    try {
      await thumbnailApi.upload(canvasId, dataUrl);
    } catch {
      // Background process, ignore failures
    }
  }, [canvasId]);

  // ── Ghost elements from AI Agent ─────────────────────────────────────────────
  const handleGhostElementsGenerated = useCallback((newGhosts: DrawableElement[]) => {
    // Add ghost elements to the canvas store so they render immediately
    setGhostElements(newGhosts);
    newGhosts.forEach(el => {
      useCanvasStore.getState().addElement(el);
    });
    addToast(`AI generated ${newGhosts.length} element${newGhosts.length !== 1 ? 's' : ''} — Tab to accept`, 'info', 6000);
  }, [addToast]);

  const handleGhostAccept = useCallback(() => {
    if (ghostElements.length === 0) return;
    // Commit: clear the ghost flag and emit to socket
    ghostElements.forEach(el => {
      useCanvasStore.getState().updateElement(el.id, { isGhostSuggestion: false } as any);
      const updated = useCanvasStore.getState().elements.find(e => e.id === el.id);
      if (updated) emitElementAdd(toAPI(updated));
    });
    pushHistory([...useCanvasStore.getState().elements]);
    setGhostElements([]);
    addToast(`Accepted ${ghostElements.length} AI element${ghostElements.length !== 1 ? 's' : ''}`, 'success', 2000);
  }, [ghostElements, pushHistory, emitElementAdd, addToast]);

  const handleGhostDismiss = useCallback(() => {
    if (ghostElements.length === 0) return;
    ghostElements.forEach(el => {
      useCanvasStore.getState().removeElement(el.id);
    });
    setGhostElements([]);
    addToast('AI suggestions dismissed', 'info', 1500);
  }, [ghostElements, addToast]);

  // ── Keyboard shortcuts ────────────────────────────────────────────────────────
  // We need a ref for the clipboard copy state since useEffect captures the initial scope
  const clipboardRef = useRef<DrawableElement[]>([]);

  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      const target = e.target as HTMLElement;
      if (target?.tagName === 'INPUT' || target?.tagName === 'TEXTAREA' || target?.isContentEditable) return;
      
      if ((e.metaKey || e.ctrlKey) && e.key === 'z') { e.preventDefault(); e.shiftKey ? handleRedo() : handleUndo(); return; }
      if ((e.metaKey || e.ctrlKey) && e.key === 's') { e.preventDefault(); handleSave(); return; }
      if ((e.metaKey || e.ctrlKey) && e.key === 'j') { e.preventDefault(); useUIStore.getState().togglePanel('aiChatOpen'); return; }
      
      // Select All
      if ((e.metaKey || e.ctrlKey) && e.key === 'a') {
        e.preventDefault();
        const { elements: currentEls, setSelectedIds } = useCanvasStore.getState();
        setSelectedIds(currentEls.map(el => el.id));
        return;
      }

      // Copy
      if ((e.metaKey || e.ctrlKey) && e.key === 'c') {
        const { selectedIds, elements: currentEls } = useCanvasStore.getState();
        if (selectedIds.length > 0) {
          clipboardRef.current = currentEls.filter((el) => selectedIds.includes(el.id));
          addToast(`Copied ${clipboardRef.current.length} element${clipboardRef.current.length > 1 ? 's' : ''}`, 'info', 1500);
        }
        return;
      }

      // Paste
      if ((e.metaKey || e.ctrlKey) && e.key === 'v') {
        if (clipboardRef.current.length > 0) {
          const { addElement, pushHistory, setSelectedIds, elements: currentEls } = useCanvasStore.getState();
          const pastedIds: string[] = [];
          
          clipboardRef.current.forEach((el) => {
             const newId = generateId();
             pastedIds.push(newId);
             const pastedEl = { ...el, id: newId, elementId: newId, timestamp: Date.now() } as any;
             
             // Offset slightly
             if (pastedEl.x !== undefined) pastedEl.x += 20;
             if (pastedEl.y !== undefined) pastedEl.y += 20;
             if (pastedEl.points) {
               pastedEl.points = pastedEl.points.map((p: any) => ({ x: p.x + 20, y: p.y + 20 }));
               pastedEl.bounds = null; // Forces recalculation during render
             }
             
             addElement(pastedEl);
             emitElementAdd(toAPI(pastedEl));
          });
          
          setSelectedIds(pastedIds);
          pushHistory([...useCanvasStore.getState().elements]);
        }
        return;
      }

      // Duplicate
      if ((e.metaKey || e.ctrlKey) && e.key === 'd') {
        e.preventDefault();
        const { selectedIds, elements: currentEls, addElement, pushHistory, setSelectedIds } = useCanvasStore.getState();
        if (selectedIds.length > 0) {
          const dupedIds: string[] = [];
          const toDup = currentEls.filter((el) => selectedIds.includes(el.id));
          toDup.forEach((el) => {
             const newId = generateId();
             dupedIds.push(newId);
             const dupedEl = { ...el, id: newId, elementId: newId, timestamp: Date.now() } as any;
             if (dupedEl.x !== undefined) dupedEl.x += 20;
             if (dupedEl.y !== undefined) dupedEl.y += 20;
             if (dupedEl.points) {
               dupedEl.points = dupedEl.points.map((p: any) => ({ x: p.x + 20, y: p.y + 20 }));
               dupedEl.bounds = null;
             }
             addElement(dupedEl);
             emitElementAdd(toAPI(dupedEl));
          });
          setSelectedIds(dupedIds);
          pushHistory([...useCanvasStore.getState().elements]);
          addToast(`Duplicated ${toDup.length} element${toDup.length > 1 ? 's' : ''}`, 'success', 1500);
        }
        return;
      }

      // Nudge with Arrow Keys
      if (['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight'].includes(e.key)) {
        const { selectedIds, elements: currentEls, updateElement, pushHistory } = useCanvasStore.getState();
        if (selectedIds.length > 0) {
          e.preventDefault();
          const dx = e.key === 'ArrowLeft' ? -1 : e.key === 'ArrowRight' ? 1 : 0;
          const dy = e.key === 'ArrowUp' ? -1 : e.key === 'ArrowDown' ? 1 : 0;
          const shiftMultiplier = e.shiftKey ? 10 : 1;
          const moveX = dx * shiftMultiplier;
          const moveY = dy * shiftMultiplier;
          
          let changed = false;
          selectedIds.forEach((id) => {
            const el = currentEls.find(e => e.id === id);
            if (!el) return;
            if (isStroke(el)) {
              const shifted = el.points.map(p => ({ x: p.x + moveX, y: p.y + moveY }));
              updateElement(id, { points: shifted, bounds: null } as any);
            } else if (isShape(el) || isFlowchart(el) || isTextElement(el)) {
              updateElement(id, { x: (el as any).x + moveX, y: (el as any).y + moveY } as any);
            }
            changed = true;
            const updatedEl = useCanvasStore.getState().elements.find(e => e.id === id);
            if (updatedEl) emitElementUpdate(toAPI(updatedEl));
          });
          if (changed) pushHistory([...useCanvasStore.getState().elements]);
          return;
        }
      }

      if (e.key === 'Backspace' || e.key === 'Delete') {
        const { selectedIds, setSelectedIds } = useCanvasStore.getState();
        if (selectedIds.length > 0) {
          e.preventDefault();
          handleElementDelete([...selectedIds]);
          setSelectedIds([]);
        }
      }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [handleUndo, handleRedo, handleSave, handleElementDelete, emitElementAdd, addToast]);

  const handleElementModify = useCallback((_el: DrawableElement, apiForm: unknown) => {
    emitElementUpdate(apiForm);
  }, [emitElementUpdate]);

  const handleStyleChange = useCallback((updates: Partial<DrawableElement>) => {
    const { selectedIds, updateElement, pushHistory, elements } = useCanvasStore.getState();
    if (selectedIds.length === 0) return;
    
    let changed = false;
    selectedIds.forEach(id => {
      updateElement(id, updates as any);
      
      const updatedEl = useCanvasStore.getState().elements.find(e => e.id === id);
      if (updatedEl) {
        emitElementUpdate(toAPI(updatedEl));
        changed = true;
      }
    });
    
    if (changed) {
      pushHistory([...useCanvasStore.getState().elements]);
    }
  }, [emitElementUpdate]);

  // ── Export ─────────────────────────────────────────────────────────────────────
  const handleExport = useCallback((fmt: 'png' | 'svg' | 'pdf' | 'json') => {
    exportCanvas(canvasElemRef.current, elements, useCanvasStore.getState().viewport, fmt, canvasId);
    addToast(`Exported as ${fmt.toUpperCase()}`, 'success', 2000);
  }, [elements, canvasId, addToast]);

  if (authLoading || joinLoading) {
    return (
      <div className="flex h-screen w-screen items-center justify-center bg-slate-50">
        <div className="flex flex-col items-center gap-3">
          <div className="w-10 h-10 border-3 border-emerald-500 border-t-transparent rounded-full animate-spin" />
          <p className="text-sm text-slate-500 font-medium">Loading canvas…</p>
        </div>
      </div>
    );
  }

  return (
    <div className="h-screen w-screen overflow-hidden bg-slate-50 select-none relative">
      {/* Canvas engine */}
      <CanvasEngine
        canEdit={canEdit}
        onElementAdd={handleElementAdd}
        onElementDelete={handleElementDelete}
        onElementModify={handleElementModify}
        onCursorMove={emitCursorMove}
        onStrokePreview={emitStrokePreview}
        onCanvasClear={emitCanvasClear}
        onCanvasSave={handleSave}
        onThumbnailCapture={handleThumbnailCapture}
      />

      {/* Left toolbar */}
      {canEdit && <Toolbar canEdit={canEdit} onStyleChange={handleStyleChange} />}

      {/* Top bar */}
      <TopBar
        onUndo={handleUndo}
        onRedo={handleRedo}
        onSave={handleSave}
        onExport={handleExport}
        canUndo={historyIndex > 0}
        canRedo={historyIndex < history.length - 1}
        canEdit={canEdit}
      />

      {/* Voice room (top right) */}
      <div className="absolute top-14 right-4 z-20">
        <VoiceRoom
          inVoice={inVoice}
          muted={muted}
          participants={participants}
          permissionDenied={permissionDenied}
          joining={joiningVoice}
          onJoin={handleJoinVoice}
          onLeave={leaveVoice}
          onToggleMute={toggleMute}
        />
      </div>

      {/* AI Chat Panel */}
      <AIChatPanel
        canvasId={canvasId}
        onGhostElementsGenerated={canEdit ? handleGhostElementsGenerated : undefined}
      />

      {/* Ghost Accept Bar — shown when AI has generated elements */}
      {ghostElements.length > 0 && (
        <GhostAcceptBar
          count={ghostElements.length}
          onAccept={handleGhostAccept}
          onDismiss={handleGhostDismiss}
        />
      )}

      {/* Comments Panel */}
      <AnnotationsPanel />

      {/* Branch History Panel */}
      <BranchHistoryPanel />

      {/* Share Modal */}
      <ShareModal />

      {/* Toast notifications */}
      <ToastContainer />
    </div>
  );
}
